export const  ACTION_TYPES = {
    REQUEST_SOURCES: 'REQUEST_SOURCES',
    RECEIVE_SOURCES: 'RECEIVE_SOURCES',
    SELECT_SOURCE: 'SELECT_SOURCE',
    REQUEST_NEWS: 'REQUEST_NEWS',
    RECEIVE_NEWS: 'RECEIVE_NEWS'
};

